### ISSUE TITLE
Request to add functionality

### ISSUE THREAD

**Issue by Testhaha2023** [hschickdevs/Telegram-Translate-AI#32]
This is a good project, it feels very practical, but now it's a bit troublesome to translate because my friends and I mostly translate our native language into a fixed language like English or Korean. Can the bot be given the option to set parameters that allow users to set their default source and target languages? This way, users only need to send the content they want to translate to the bot, and the robot can automatically translate it. It would feel more convenient in terms of usage

**Comment by hschickdevs** [comment]
Adding reference: https://github.com/nessshon/gtranslator-bot?tab=readme-ov-file

**Comment by hschickdevs** [comment]
Closing because we identified the /session command suits the needs.
